version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  example-job:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/update-description:
          image: docker_demo 

workflows:
  example-workflow:
    jobs:
      - example-job